import type { BattlePassResponse } from './api.dto';

export const mockBattlePass: BattlePassResponse = {
  level: 5,
  exp: 450,
  progress: 75,
  is_active: true,
  rewards: [
    {
      id: 1,
      level: 1,
      type: 'BP',
      count: 100,
      title: '100 BP',
      is_claimed: true,
      is_available: true,
      type_reward: '',
    },
    {
      id: 2,
      level: 2,
      type: 'TON',
      count: 0.5,
      title: '0.5 TON',
      is_claimed: true,
      is_available: true,
      type_reward: '',
    },
    {
      id: 3,
      level: 3,
      type: 'BP',
      count: 200,
      title: '200 BP',
      is_claimed: false,
      is_available: true,
      type_reward: '',
    },
    {
      id: 4,
      level: 4,
      type: 'GIFT',
      count: 1,
      title: 'Gift Box',
      is_claimed: false,
      is_available: true,
      type_reward: '',
    },
    {
      id: 5,
      level: 5,
      type: 'TON',
      count: 1,
      title: '1 TON',
      is_claimed: false,
      is_available: true,
      type_reward: '',
    },
    {
      id: 6,
      level: 6,
      type: 'BP',
      count: 300,
      title: '300 BP',
      is_claimed: false,
      is_available: false,
      type_reward: '',
    },
    {
      id: 7,
      level: 7,
      type: 'PREMIUM',
      count: 1,
      title: 'Premium',
      is_claimed: false,
      is_available: false,
      type_reward: '',
    },
    {
      id: 8,
      level: 8,
      type: 'STARS',
      count: 100,
      title: '100 Stars',
      is_claimed: false,
      is_available: false,
      type_reward: '',
    },
    {
      id: 9,
      level: 9,
      type: 'BP',
      count: 500,
      title: '500 BP',
      is_claimed: false,
      is_available: false,
      type_reward: '',
    },
    {
      id: 10,
      level: 10,
      type: 'TON',
      count: 5,
      title: '5 TON',
      is_claimed: false,
      is_available: false,
      type_reward: '',
    },
  ],
};
