import type { ApiTask } from './api.dto';

export const mockApiTasks: ApiTask[] = [
  {
    id: 1,
    type: 'SET_BIO',
    goal_count: 1,
    reward_ton: 0.1,
    reward_bp: null,
    reward_exp: 10,
    progress: { current_count: 1, status: 'REWARDED' },
  },
  {
    id: 2,
    type: 'SET_NICK',
    goal_count: 1,
    reward_ton: 0.1,
    reward_bp: null,
    reward_exp: 10,
    progress: { current_count: 1, status: 'COMPLETED' },
  },
  {
    id: 3,
    type: 'SET_STORY',
    goal_count: 1,
    reward_ton: 0.2,
    reward_bp: null,
    reward_exp: 20,
    progress: { current_count: 0, status: 'ACTIVE' },
  },
  {
    id: 4,
    type: 'INVITE',
    goal_count: 3,
    reward_ton: 0.5,
    reward_bp: 50,
    reward_exp: 50,
    progress: { current_count: 1, status: 'ACTIVE' },
  },
  {
    id: 5,
    type: 'CREATE_ORDER',
    goal_count: 1,
    reward_ton: null,
    reward_bp: 100,
    reward_exp: 30,
    progress: null,
  },
  {
    id: 6,
    type: 'BUY_ORDER',
    goal_count: 1,
    reward_ton: null,
    reward_bp: 100,
    reward_exp: 30,
    progress: null,
  },
  {
    id: 7,
    type: 'CONNECT_WALLET',
    goal_count: 1,
    reward_ton: 0.3,
    reward_bp: null,
    reward_exp: 25,
    progress: { current_count: 1, status: 'REWARDED' },
  },
];

export const mockBonusTasks: ApiTask[] = [
  {
    id: 101,
    type: 'SELF_BUY_ORDER',
    goal_count: 5,
    reward_ton: 1.0,
    reward_bp: 200,
    reward_exp: 100,
    progress: { current_count: 2, status: 'ACTIVE' },
  },
  {
    id: 102,
    type: 'SUM_PAYMENT',
    goal_count: 10,
    reward_ton: 2.0,
    reward_bp: 500,
    reward_exp: 200,
    progress: { current_count: 5, status: 'ACTIVE' },
  },
  {
    id: 103,
    type: 'SUM_EARN_REF',
    goal_count: 100,
    reward_ton: 5.0,
    reward_bp: 1000,
    reward_exp: 500,
    progress: null,
  },
];
