import type { Order } from './api.dto';

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    owner: {
      id: 1,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
      name: 'Alex Johnson',
      username: 'alex_j',
    },
    initial_bp_amount: 1000,
    initial_ton_amount: 50,
    current_ton_amount: 25,
    status: 'PARTIAL',
    create_date: Date.now() - 12 * 60000,
  },
  {
    id: 2,
    owner: {
      id: 2,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      name: 'Sarah Miller',
      username: 'sarah_m',
    },
    initial_bp_amount: 500,
    initial_ton_amount: 100,
    current_ton_amount: 100,
    status: 'OPEN',
    create_date: Date.now() - 5 * 60000,
  },
  {
    id: 3,
    owner: {
      id: 3,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      name: 'Mike Chen',
      username: 'mike_c',
    },
    initial_bp_amount: 2000,
    initial_ton_amount: 200,
    current_ton_amount: 150,
    status: 'OPEN',
    create_date: Date.now() - 45 * 60000,
  },
  {
    id: 4,
    owner: {
      id: 4,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      name: 'Emma Wilson',
      username: 'emma_w',
    },
    initial_bp_amount: 750,
    initial_ton_amount: 75,
    current_ton_amount: 75,
    status: 'OPEN',
    create_date: Date.now() - 2 * 3600000,
  },
  {
    id: 5,
    owner: {
      id: 5,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
      name: 'David Brown',
      username: 'david_b',
    },
    initial_bp_amount: 1500,
    initial_ton_amount: 150,
    current_ton_amount: 50,
    status: 'PARTIAL',
    create_date: Date.now() - 1 * 3600000,
  },
  {
    id: 6,
    owner: {
      id: 6,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      name: 'Lisa Taylor',
      username: 'lisa_t',
    },
    initial_bp_amount: 3000,
    initial_ton_amount: 300,
    current_ton_amount: 300,
    status: 'OPEN',
    create_date: Date.now() - 3 * 3600000,
  },
  {
    id: 7,
    owner: {
      id: 7,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      name: 'John Davis',
      username: 'john_d',
    },
    initial_bp_amount: 800,
    initial_ton_amount: 80,
    current_ton_amount: 80,
    status: 'OPEN',
    create_date: Date.now() - 6 * 3600000,
  },
  {
    id: 8,
    owner: {
      id: 8,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna',
      name: 'Anna Martinez',
      username: 'anna_m',
    },
    initial_bp_amount: 2500,
    initial_ton_amount: 250,
    current_ton_amount: 100,
    status: 'PARTIAL',
    create_date: Date.now() - 12 * 3600000,
  },
  {
    id: 9,
    owner: {
      id: 9,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom',
      name: 'Tom Anderson',
      username: 'tom_a',
    },
    initial_bp_amount: 600,
    initial_ton_amount: 60,
    current_ton_amount: 60,
    status: 'OPEN',
    create_date: Date.now() - 24 * 3600000,
  },
  {
    id: 10,
    owner: {
      id: 10,
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kate',
      name: 'Kate Robinson',
      username: 'kate_r',
    },
    initial_bp_amount: 1200,
    initial_ton_amount: 120,
    current_ton_amount: 120,
    status: 'OPEN',
    create_date: Date.now() - 2 * 86400000,
  },
];
